(function(){
  const {$,$$,esc,state,saveFirms,setDefaultFirm,getDefaultFirm,validIBAN}=App;

  function renderFirmSelect(){ const sel=$('#firm_select'); if(!sel) return; sel.innerHTML=''; if(!state.firms.length){ sel.innerHTML='<option value="">—</option>'; return; } state.firms.forEach(f=>sel.append(new Option((String(f.id)===String(state.defaultFirmId)?'★ ':'')+f.name,f.id))); if(!sel.value&&state.firms.length) sel.value=String(state.defaultFirmId||state.firms[0].id); }

  function renderFirmSummary(){ const box=$('#firm_summary'); if(!box) return; const f=getDefaultFirm(); if(!f){ box.innerHTML='<div class="muted">Keine Standard-Firma.</div>'; return;} box.innerHTML=`<div>Name</div><div>${esc(f.name||'')}</div><div>IBAN</div><div>${esc(f.iban||'')}</div><div>Adresse</div><div>${esc(f.street||'')} ${esc(f.no||'')}</div><div>Ort</div><div>${esc(f.zip||'')} ${esc(f.city||'')}</div><div>Land</div><div>${esc(f.country||'')}</div>`; }

  function renderFirmList(){ const tb=$('#firm_list'); if(!tb) return; if(!state.firms.length){ tb.innerHTML='<tr><td colspan="7" class="muted">Noch keine Firma.</td></tr>'; renderFirmSelect(); renderFirmSummary(); return; } tb.innerHTML=''; state.firms.forEach((f,i)=>{ const tr=document.createElement('tr'); const addr=`${esc(f.street||'')} ${esc(f.no||'')}`.trim(); const place=`${esc(f.zip||'')} ${esc(f.city||'')}`.trim(); tr.innerHTML=`<td>${esc(f.name||'')} ${String(f.id)===String(state.defaultFirmId)?'<span class="badge default">STD</span>':''}</td><td><span class="pill">${esc(f.iban||'')}</span></td><td>${addr}</td><td>${place}</td><td>${esc(f.country||'')}</td><td>${String(f.id)===String(state.defaultFirmId)?'★':''}</td><td class="right"><button class="btn sm" data-act="def" data-idx="${i}" title="Standard">★</button><button class="btn sm" data-act="edit" data-idx="${i}">Edit</button><button class="btn warn sm" data-act="del" data-idx="${i}">✕</button></td>`; tb.append(tr); }); renderFirmSelect(); renderFirmSummary(); }

  function resetFirmForm(){ ['cred_name','cred_iban','cred_street','cred_no','cred_zip','cred_city'].forEach(id=>{const el=$('#'+id); if(el) el.value='';}); const country=$('#cred_country'); if(country) country.value='CH'; const logo=$('#cred_logo'); if(logo) logo.value=''; const prev=$('#cred_logo_preview'); if(prev){ prev.src=''; prev.style.display='none'; } const fb=$('#cred_logo_feedback'); if(fb) fb.textContent=''; const addBtn=$('#add_firm'); const updBtn=$('#update_firm'); const cancelBtn=$('#cancel_update_firm'); addBtn?.classList.remove('hidden'); updBtn?.classList.add('hidden'); cancelBtn?.classList.add('hidden'); const status=$('#firm_form_status'); if(status) status.textContent=''; editingFirmIdx=null; }

  let editingFirmIdx=null; let currentLogoData=null;

  $('#cred_logo')?.addEventListener('change', e=>{ const file=e.target.files && e.target.files[0]; const prev=$('#cred_logo_preview'); const fb=$('#cred_logo_feedback'); if(!file){ if(prev) prev.style.display='none'; if(fb) fb.textContent=''; currentLogoData=null; return; } if(!/^image\/(png|jpeg|webp)$/.test(file.type)){ if(fb) fb.textContent='Nur PNG/JPG/WEBP'; e.target.value=''; return; } if(file.size>500*1024){ if(fb) fb.textContent='Bild > 500KB'; e.target.value=''; return; } const r=new FileReader(); r.onload=ev=>{ currentLogoData=ev.target.result; if(prev){prev.src=currentLogoData; prev.style.display='block';} if(fb) fb.textContent='Logo gewählt'; }; r.readAsDataURL(file); });

  $('#add_firm')?.addEventListener('click',()=>{ const name=$('#cred_name').value.trim(); const iban=$('#cred_iban').value.trim(); const street=$('#cred_street').value.trim(); const no=$('#cred_no').value.trim(); const zip=$('#cred_zip').value.trim(); const city=$('#cred_city').value.trim(); const country=$('#cred_country').value; const st=$('#firm_form_status'); st.textContent=''; if(!name||!iban||!street||!zip||!city){ st.textContent='Pflichtfelder fehlen.'; return; } if(!App.validIBAN(iban)){ st.textContent='IBAN ungültig.'; return; } const f={id:Date.now(),name,iban,street,no,zip,city,country,logo:currentLogoData||null}; if(!state.firms.length) state.defaultFirmId=f.id; state.firms.push(f); saveFirms(); resetFirmForm(); st.textContent='Gespeichert.'; renderFirmList(); });

  $('#firm_table')?.addEventListener('click', e=>{ const b=e.target.closest('button'); if(!b) return; const idx=Number(b.dataset.idx); const f=state.firms[idx]; if(!f) return; const act=b.dataset.act; if(act==='del'){ if(!confirm('Firma löschen?')) return; const wasDef=String(f.id)===String(state.defaultFirmId); state.firms.splice(idx,1); if(wasDef) state.defaultFirmId=state.firms[0]?.id||null; saveFirms(); renderFirmList(); return; } if(act==='def'){ state.defaultFirmId=f.id; saveFirms(); renderFirmList(); return; } if(act==='edit'){ editingFirmIdx=idx; $('#cred_name').value=f.name||''; $('#cred_iban').value=f.iban||''; $('#cred_street').value=f.street||''; $('#cred_no').value=f.no||''; $('#cred_zip').value=f.zip||''; $('#cred_city').value=f.city||''; $('#cred_country').value=f.country||'CH'; const prev=$('#cred_logo_preview'); if(prev && f.logo){ prev.src=f.logo; prev.style.display='block'; } $('#add_firm').classList.add('hidden'); $('#update_firm').classList.remove('hidden'); $('#cancel_update_firm').classList.remove('hidden'); $('#firm_form_status').textContent='Bearbeitung aktiv'; window.scrollTo({top:0,behavior:'smooth'}); return; } if(act==='save'){ /* unused in this page */ }
  });

  $('#update_firm')?.addEventListener('click',()=>{ if(editingFirmIdx==null) return; const f=state.firms[editingFirmIdx]; if(!f) return; const name=$('#cred_name').value.trim(); const iban=$('#cred_iban').value.trim(); const street=$('#cred_street').value.trim(); const no=$('#cred_no').value.trim(); const zip=$('#cred_zip').value.trim(); const city=$('#cred_city').value.trim(); const country=$('#cred_country').value; if(!name||!iban||!street||!zip||!city){ $('#firm_form_status').textContent='Pflichtfelder fehlen.'; return; } if(!App.validIBAN(iban)){ $('#firm_form_status').textContent='IBAN ungültig.'; return; } Object.assign(f,{name,iban,street,no,zip,city,country}); if(currentLogoData) f.logo=currentLogoData; saveFirms(); $('#firm_form_status').textContent='Änderungen gespeichert'; setTimeout(()=>$('#firm_form_status').textContent='',1200); resetFirmForm(); renderFirmList(); });

  $('#cancel_update_firm')?.addEventListener('click', resetFirmForm);

  renderFirmList();
})();